# Generated by Django 4.1.6 on 2023-02-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BearHubHome', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
