# Generated by Django 4.1.6 on 2023-02-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BearHubHome', '0003_student_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField(max_length=24)),
                ('point_value', models.IntegerField()),
                ('students', models.ManyToManyField(blank=True, related_name='student', to='BearHubHome.student')),
            ],
        ),
    ]
