# Generated by Django 4.1.6 on 2023-02-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BearHubHome', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=64)),
                ('Last_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='event', to='BearHubHome.student'),
        ),
    ]
