# Generated by Django 4.1.6 on 2023-02-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BearHubHome', '0006_alter_adminuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='None', max_length=512),
            preserve_default=False,
        ),
    ]
