# Generated by Django 4.1.6 on 2023-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BearHubHome', '0009_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='kevin212007@icloud.com', max_length=254),
            preserve_default=False,
        ),
    ]
